config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do 
    resources :profiles
    resources :addresses
  end
  resources :cars
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    scope :search_for, -> (query) {
        where(
            arel_table[:brand].matches("%#{query}%")
            .or(arel_table[:model].matches("%#{query}%"))
            .or(arel_table[:registration_number].matches("%#{query}%"))
        )
        .order(arel_table[:id].asc)
      }
end

app/models/profile.rb
class Profile < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_one :profile
    has_many :addresses

    default_scope { includes(:profile) }

    scope :search_for, -> (query) {
        where(
            arel_table[:name].matches("%#{query}%")
            .or(arel_table[:email].matches("%#{query}%"))
            .or(Profile.arel_table[:name].matches("%#{query}%"))
        )
        .references(:profile)
        .order(arel_table[:id].asc)
      }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
    before_action :set_params, only: [:show, :edit, :update, :destroy]
    before_action :set_user, only:[:index, :new, :create, :show, :edit, :update, :destroy]
    def index
        @addresses = Address.all
    end

    def new
        @address = Address.new
    end

    def edit
    end

    def create
        @address = Address.new(address_params)
        @address.user = @user
        respond_to do |format|
            if @address.save
                format.html{redirect_to [@user, @address]}
                format.json{render :show, status: :created, location: [@user, @address]}
            else
                format.html{render :new}
                format.json{render json:@address.error ,status: :unprocessable_entity}
            end
        end
    end

    def update
        respond_to do |format|
            if @address.update(address_params)
                format.html{redirect_to [@user, @address]}
                format.json{render :show, status: :ok, location: [@user, @address]}
            else
                format.html{render :new}
                format.json{render json:@address.error ,status: :unprocessable_entity}
            end
        end
    end
    
    def destroy
        @address.destroy
        respond_to do |format|
            format.html{redirect_to user_addresses_path}
            format.json{ head:no_content}
        end
    end

    private

    def set_user
        @user = User.find(params[:user_id])
    end

    def set_params
        @address = Address.find(params[:id])
    end

    def address_params
        params.require(:address).permit(:name, :city, :state, :country )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    respond_to :html, :json, :js
    before_action :set_car, only:[:show, :edit, :update, :destroy]
    def index
        if params[:search_for].present?
          @cars = Car.search_for(params[:search_for])
        else
          @cars = Car.all
        end
      end

    def show
    end

    def new
        @car= Car.new
    end

    def edit
    end

    def create
        @car= Car.new(car_params)
        respond_to do |format|
            if @car.save
                format.html{redirect_to @car}
            else
                format.html{render:new}
            end
        end
    end

    def update
        respond_to do |format|
            if @car.update(car_params)
                format.html{redirect_to @car}
            else
                format.html{render:edit}
            end
        end
    end

    def destroy
        @car.destroy
        respond_to do |format|
            format.html{redirect_to @car}
        end
    end

    private

    def set_car
        @car= Car.find(params[:id])
    end

    def car_params
        params.require(:car).permit(:brand, :model, :registration_number, :colour )
    end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_profile, only:[:show, :edit, :update, :destroy]
    before_action :set_user, only:[:index, :new, :create, :show, :edit, :update, :destroy]

    def index
        @profiles = Profile.all
    end

    def show
    end

    def new
        @profile = Profile.new
    end
     
    def edit
    end

    def create
        @profile = Profile.new(profile_params)
        @profile.user = @user
        respond_to do |format|
            if @profile.save
                format.html{redirect_to [@user,@profile]}
                format.json{render:show , status: :created ,location: [@user,@profile]}
            else
                format.html{render :new}
                format.json{render json:@profile.error, status: :unprocessable_entity}
            end
        end
    end

    def update
        respond_to do |format|
            if @profile.update(profile_params)
                format.html{redirect_to [@user,@profile]}
                format.json{render:show , status: :ok ,location: [@user,@profile]}
            else
                format.html{render :edit}
                format.json{render json:@profile.error, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @profile.destroy
        respond_to do |format|
            format.html{redirect_to profiles_path}
        end
    end

    private

    def set_user
        @user = User.find(params[:user_id])
    end

    def set_profile
        @profile = Profile.find(params[:id])
    end

    def profile_params
        params.require(:profile).permit(:name ,:age ,:sex ,:phone_number)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html, :json, :js
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search_for].present?
      @users = User.search_for(params[:search_for])
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :conform_password)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for([@user, @address]) do |f| %>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>   
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', [@user, @address] %> |
<%= link_to 'Back', user_addresses_path %>

app/views/addresses/index.html.erb
<h1>Address</h1>
<table>
    <thread>
        <tr>
            <th>Name</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
        </tr>
    </thread>
<tbody>
    <% @addresses.each do |address| %>
        <tr>
            <th><%= address.name %></th>
            <th><%= address.city %></th>
            <th><%= address.state %></th>
            <th><%= address.country %></th>
            <th><%= link_to 'Show', user_address_path(address.user, address) %></th>
            <th><%= link_to 'Edit', edit_user_address_path(address.user, address) %></th>
            <th><%= link_to 'Destroy', user_address_path(address.user, address) ,method: :delete,data: {confirm: 'Are you sure?'} %></th>
        </tr>
    <% end %>
</tbody>
</table>
<br>
<%= link_to 'New Address', new_user_address_path(@user) %><br>
<%= link_to 'Users', @user %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Back', user_addresses_path(@user) %>

app/views/addresses/show.html.erb
<p>
<strong>Name:</strong>
<%= @address.name %>
</p>

<p>
<strong>City:</strong>
<%= @address.city %>
</p>

<p>
<strong>State:</strong>
<%= @address.state %>
</p>

<p>
<strong>Country:</strong>
<%= @address.country %>
</p>

<%= link_to 'Edit', edit_user_address_path(@user, @address) %> |
<%= link_to 'Back', user_addresses_path(@user) %>

app/views/cars/_car_list.html.erb
<table>
<thread>
    <tr>
        <th>Brand Name</th>
        <th>Model</th>
        <th>Registration Number</th>
        <th>Colour</th>
    </tr>
</thread>
<tbody>
<% @cars.each do |car| %>
    <tr>
        <th><%= car.brand %></th>
        <th><%= car.model %></th>
        <th><%= car.registration_number %></th>
        <th><%= car.colour %></th>
        <th><%= link_to 'Show', car_path(car) %></th>
        <th><%= link_to 'Edit', edit_car_path(car) %></th>
        <th><%= link_to 'Destroy', car_path(car) ,method: :delete,data: {confirm: 'Are you sure?'} %></th>
    </tr>
<% end %>
</tbody>
</table>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
    <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :registaration_number %>
    <%= f.text_field :registration_number %>
  </div>

  <div class="field">
    <%= f.label :colour %>
    <%= f.text_field :colour %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>   
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Cars</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Car</h1>
<%=  render :partial=> 'common/search', locals: {placeholder: 'search for cars', search_url: url_for(cars_path(format: :js))} %>
<div id="car_list">
<%=  render :partial=> 'car_list' %> 
</div>
<br>
<%= link_to 'New Car', new_car_path %><br>

app/views/cars/index.js.erb
$('#car_list').html('<%= escape_javascript render(:partial =>'cars/car_list') %>');

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car%>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p>
<strong>Brand Name:</strong>
<%= @car.brand %>
</p>

<p>
<strong>Mdel:</strong>
<%= @car.model %>
</p>

<p>
<strong>Registartion Number:</strong>
<%= @car.registration_number %>
</p>

<p>
<strong>Colour:</strong>
<%= @car.colour %>
</p>

<%= link_to 'Edit', edit_car_path %> |
<%= link_to 'Back', cars_path %>

app/views/common/_search.html.erb
<input type="text" placeholder="<%= placeholder%>" style="margin-top: 10px" id="search">

<script>
var searchTimer;
$("#search").keyup(function(){
    clearTimeout(searchTimer);
    searchTimer= setTimeout(doSearch,500);
});

function doSearch(){
    $.ajax({
        url :'<%= search_url%>',
        type:'GET',
        data:{ search_for:$('#search').val()}
    });
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for([@user, @profile]) do |f| %>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>   
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>


<%= link_to 'Back', @user %>

app/views/profiles/index.html.erb
<h1>Profile</h1>
<table>
    <thread>
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Sex</th>
            <th>Phone Number</th>
        </tr>
    </thread>
<tbody>
    <% @profiles.each do |profile| %>
        <tr>
            <th><%= profile.name %></th>
            <th><%= profile.age %></th>
            <th><%= profile.sex %></th>
            <th><%= profile.phone_number %></th>
            <th><%= link_to 'Show', user_profile_path(profile.user,profile) %></th>
            <th><%= link_to 'Edit', edit_user_profile_path(profile.user,profile) %></th>
            <th><%= link_to 'Destroy', user_profile_path(profile.user,profile) ,method: :delete,data: {confirm: 'Are you sure?'} %></th>
        </tr>
    <% end %>
</tbody>
</table>
<br>
<%= link_to 'New Profile', new_user_profile_path(@user) %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', user_profiles_path %>

app/views/profiles/show.html.erb
<p>
<strong>Name:</strong>
<%= @profile.name %>
</p>

<p>
<strong>Age:</strong>
<%= @profile.age %>
</p>

<p>
<strong>Sex:</strong>
<%= @profile.sex %>
</p>

<p>
<strong>Phone Number:</strong>
<%= @profile.phone_number %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user,@profile) %> |
<%= link_to 'Back', @user %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :conform_password %>
    <%= f.text_field :conform_password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user_list.html.erb
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Conform password</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= user.conform_password %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<%= render :partial=> 'common/search', locals: {placeholder: 'search for users', search_url: url_for(users_path(format: :js))} %>
<div id="user_list">
  <%= render :partial=>'user_list' %>
</div>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/index.js.erb
$('#user_list').html('<%= escape_javascript render(:partial =>'users/user_list') %>');

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Conform password:</strong>
  <%= @user.conform_password %>
</p>

<% if (@user.profile.present?) %>
  <%= link_to 'Edit Profile', edit_user_profile_path(@user, @user.profile) %>
<% else %>
  <%= link_to 'Create Profile', new_user_profile_path(@user) %>
<% end %>
<br>
<%= link_to 'address Page', user_addresses_path(@user) %><br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>